version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: culinary_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=culinary_api.settings
    volumes:
      - ./:/opt/app
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - culinary_network
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn culinary_api.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: mysql:8.0
    container_name: culinary_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - culinary_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: culinary_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - culinary_network

volumes:
  db_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  culinary_network:
    driver: bridge